### ISSUE TITLE
Wordpress always returns as having found something

### ISSUE THREAD

**Issue by perfetti** [senran101604/sagemode#1] opened 2023-10-17 15:49 UTC
Due to wordpress redirecting when you go to a missing subdomain, we get a false positive on that check.

`https://doesnotexistdontchaknow.wordpress.com` redirects to `https://wordpress.com/typo/?subdomain=doesnotexistdontchaknow`. which is how we would know it's actually an invalid link.

**Comment by senran101604** [comment] 2023-11-18 16:41
Duplicate of #3 , It's fixed now thank you

**Closed as completed by senran101604** 2023-11-18 16:41 UTC
